trigger:
- main

pool:
  name: 'my-self-hosted-agent'

variables:
  buildConfiguration: 'Release'
  publishFolder: '$(Build.ArtifactStagingDirectory)/publish'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '9.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: dotnet clean
      displayName: 'Clean Solution'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.sln'
      displayName: 'Restore NuGet Packages'

    - task: VSBuild@1
      inputs:
        solution: '**/*.sln'
        configuration: '$(buildConfiguration)'
      displayName: 'Build Solution'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(publishFolder)'
        zipAfterPublish: false
      displayName: 'Publish Application'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(publishFolder)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish Build Artifacts'

- stage: Deploy_Dev
  displayName: 'Deploy to Dev'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        downloadPath: '$(Pipeline.Workspace)'
      displayName: 'Download Build Artifacts'

    - script: |
        # Add script to deploy to Dev VM (e.g., copy files, configure IIS)
        echo "Deploying to Dev environment..."
        $sourcePath = "$(Pipeline.Workspace)\drop"
        $destinationPath = "\\dev-server\C$\inetpub\PhoneSeller"
        Copy-Item -Path $sourcePath\* -Destination $destinationPath -Recurse -Force
      displayName: 'Deploy to Dev'
      env:
        DEV_SERVER_USER: $(DevServerUser)
        DEV_SERVER_PASSWORD: $(DevServerPassword)

- stage: Approve_Production
  displayName: 'Approve Production Deployment'
  dependsOn: Deploy_Dev
  jobs:
  - job: WaitForApproval
    displayName: 'Wait for Approval'
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: 'your-email@example.com'
        instructions: 'Please approve the deployment to production.'
      displayName: 'Wait for Approval'

- stage: Deploy_Production
  displayName: 'Deploy to Production'
  dependsOn: Approve_Production
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        downloadPath: '$(Pipeline.Workspace)'
      displayName: 'Download Build Artifacts'

    - script: |
        # Add script to deploy to Production VM (e.g., copy files, configure IIS)
        echo "Deploying to Production environment..."
        $sourcePath = "$(Pipeline.Workspace)\drop"
        $destinationPath = "\\prod-server\C$\inetpub\PhoneSeller"
        Copy-Item -Path $sourcePath\* -Destination $destinationPath -Recurse -Force
      displayName: 'Deploy to Production'
      env:
        PROD_SERVER_USER: $(ProdServerUser)
        PROD_SERVER_PASSWORD: $(ProdServerPassword)
